export default {
  // CARGA DE HEROES
  LOAD_CHARACTERS: 'LOAD_CHARACTERS',
  LOAD_CHARACTERS_EXIT: 'LOAD_CHARACTERS_EXIT',
  LOAD_CHARACTERS_ERROR: 'LOAD_CHARACTERS_ERROR',
  // CARGA DE COMICS A LOS QUE PERTENECE UN PERSONAJE
  LOAD_COMICS: 'LOAD_COMICS',
  LOAD_COMICS_EXIT: 'LOAD_COMICS_EXITO',
  LOAD_COMICS_ERROR: 'LOAD_COMICS_ERROR',
  // FAVORITOS CARGA AÑADIR Y ELIMINAR
  LOAD_ALL_FAVORITES: 'LOAD_ALL_FAVORITES',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  DELETE_FROM_FAVORITES: 'DELETE_FROM_FAVORITES'
};
