export default {
  // CARGA DE HEROES
  LOAD_CHARACTERS: 'LOAD_CHARACTERS',
  LOAD_CHARACTERS_EXIT: 'LOAD_CHARACTERS_EXIT',
  LOAD_CHARACTERS_ERROR: 'LOAD_CHARACTERS_ERROR',
  // HEROES FILTRADOS
  FILTER_CHARACTERS: 'FILTER_CHARACTERS',
  FILTER_CHARACTERS_EXITO: 'FILTER_CHARACTERS_EXITO',
  FILTER_CHARACTERS_ERROR: 'FILTER_CHARACTERS_ERROR'
};
